name: "WS to REST Bridge"
slug: ws_rest_bridge
version: "1.0.0"
description: "WebSocket to Home Assistant REST API bridge"
url: "https://github.com/johan-krrn/NestorSmartHomeAutomation"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
hassio_role: default
init: false
startup: application
boot: auto
ports:
  8765/tcp: 8765
ports_description:
  8765/tcp: "WebSocket server port"
options:
  ha_token: ""
  ws_port: 8765
  allowed_methods:
    - POST
    - PUT
    - DELETE
schema:
  ha_token: str
  ws_port: port
  allowed_methods:
    - "list(match(^(GET|POST|PUT|DELETE|PATCH)$))"